services:
    netviz:
        build:
            context: .
        volumes:
            - ./data:/app/data
        ports:
            - "${HOST:-127.0.0.1}:8201:8201"
        restart: unless-stopped
        logging:
            options:
                max-size: 256m
